config/routes.rb
Rails.application.routes.draw do

 root to: "static_pages#home"

 get '/home' => 'static_pages#home', as: :home

 get '/contact' => 'static_pages#contact'

 get '/about' => 'static_pages#about'

  get '/login'     => 'sessions#new', as: :new_session
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :users

  get "/wines" => "wines#index"
  get "/wines/new" => "wines#new", as: :new_wine
  get "/wines/:id" => "wines#show", as: :wine
  post "/wines/" => "wines#create"
  patch "/wines/:id" => "wines#update"
  delete "/wines/:id" => "wines#destroy"
  get "/wines/:id/edit" => "wines#edit", as: :edit_wine

  get "/wines/:wine_id/reviews/new" => "reviews#new", as: :new_wine_review
  get "/wines/:wine_id/reviews/:id" => "reviews#show", as: :review
  post "/wines/:wine_id/reviews/" => "reviews#create", as: :wine_reviews
  patch "/wines/:wine_id/reviews/:id" => "reviews#update"
  delete "/wines/:wine_id/reviews/:id" => "reviews#destroy"
  get "/wines/:wine_id/reviews/:id/edit" => "reviews#edit", as: :edit_review

  

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :wine
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews 
end

app/models/wine.rb
class Wine < ActiveRecord::Base
	has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method  :current_user
  include SessionsHelper


end

app/controllers/concerns/about_us_controller.rb
class About_Us < ActiveRecord::Base
	
    def about_us
      render text: "Include About Us infor here"
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	def show
 		@review = Review.find(params[:id])
	end

	def new
		@review = Review.new
		@wine = Wine.find(params[:wine_id])
		
	end

	def create
		@wine = Wine.find(params[:wine_id])

		@user = current_user

		@review = @wine.reviews.new({
			comments: review_params[:comments],
			paired_with: review_params[:paired_with],
			rating: review_params[:rating],

			user_id: current_user.id
			})

		if @review.save
			redirect_to wine_path(@wine)
		else
			render :new
		end

	end

	def edit
  		@review = Review.find(params[:id])
	end

	def update
  		@review = Review.find(params[:id])

  			if @review.update_attributes(review_params)
    			redirect_to reviews_path
  			else
 	   			render :edit
  			end
	end

	def destroy
		@review = Review.find(params[:id])
  		@review.destroy
  		redirect_to review_path
	end

	private
	def review_params
		params.require(:review).permit(:comments, :paired_with, :rating)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password]) 
      session[:user_id] = user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to wines_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

	def index
  		@wines = Wine.all
	end

	def show
 		@wine = Wine.find(params[:id])
	end

	def new
		@wine = Wine.new
	end

	def create
		@wine = Wine.new(params.require(:wine).permit(:country, :region, :producer, :vineyard, :predominant_variety, :vintage) )

		if @wine.save
			redirect_to wines_path
		else
			render :new
		end
	end

	def edit
  		@wine = Wine.find(params[:id])
	end

	def update
  		@wine = Wine.find(params[:id])

  			if @wine.update_attributes(params.require(:wine).permit(:country, :region, :producer, :vineyard, :predominant_variety, :vintage))
    			redirect_to wines_path
  			else
 	   			render :edit
  			end
	end

	def destroy
  		@wine = Wine.find(params[:id])
  		@wine.destroy
  		redirect_to wines_path
	end

	private
	def wine_params
  		@wine = Wine.new(params.require(:wine).permit(:country, :region, :producer, :vineyard, :predominant_variety, :vintage) )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
 	@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/ssessions_helper.rb
module SsessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> 
      <%= link_to "Third Leaf Vineyard Consulting", home_path, :class => "navbar-brand" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", "/home" %></li>
        <li><%= link_to "About", "/about" %> </li>
        <li><%= link_to "Contact", "/contact" %> <li>
        <li><%= link_to "Wines", wines_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Members Area<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log In", new_session_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Reviews</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keith</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	You are logged in as <%= current_user.email %> <br>
	<%= link_to "Log Out", logout_path, method: :delete %>
<%end%>

<%= render 'layouts/nav' %>

<div class="container"> 
	<%= yield %>
</div>


</body>
</html>

app/views/reviews/index.html.erb
<h1>Users</h1>

<table class="table table-striped, table-bordered">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Back To Wine List", wine_path %>

app/views/reviews/new.html.erb
<%= form_for [@wine, Review.new] do |f|%>

<div class="field">
    <%= f.label :comments%><br>
    <%= f.text_field :comments %>
</div>

<div class="field">
    <%= f.label :paired_with %><br>
    <%= f.text_field :paired_with %>
</div>

<div class="field">
    <%= f.label :rating %><br>
    <%= f.text_area :rating %>
</div>

<div class="actions">
    <%= f.submit %>
</div>

<% end %>

<%= link_to "Back To Wine List", wines_path %> <br>
<%= link_to "About", "/about" %> <br>
<%= link_to "Contact", "/contact" %> <br>
<%= link_to "Home", "/home" %>

app/views/static_page/index.html.erb
<h1>  Third Leaf Vineyard Consulting </h1>

app/views/static_pages/about.html.erb
<h1>About Third Leaf Vineyard Consulting</h1>

<p>
After a 35-year career in medical instrumentation sales, Keith McConnell attended Napa Valley College where he earned degrees in Viticulture and Wine Sales and Marketing.  He started Third Leaf Vineyard Consulting in 2007 and specializes in the installation of residential vineyards that range from 1/4 acre to 1 1/2 acres.  He is experienced in establishing new vineyards or reviving neglected ones.  Services offered include trellising, irrigation, soil testing, pest management and diagnosis of diseases. </p>


<%= link_to "Review A Wine You've Had", new_wine_path, :class => "btn btn-success" %>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>



<p>Third Leaf Vineyard Consulting <br>
Keith McConnell <br>	
Owner/Viticulturalist <br>
(925) 209-5710</p>


<%= link_to "Review A Wine You've Had", new_wine_path, :class => "btn btn-success" %>

app/views/static_pages/home.html.erb
<h1>Third Leaf Vineyard Consulting </h1>


<%= image_tag "vinyard.jpg" , class: "vinyardImg" %><br>





<%= link_to "Review A Wine You've Had", new_wine_path, :class => "btn btn-success" %> <br>

<%= link_to "Log Out", logout_path, method: :delete %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.firstname %></li>
  <% end %>
</ul>


<%= link_to "Review A Wine You've Had", new_wine_path, :class => "btn btn-success" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

<div class="form-group">
    <%= f.text_field :firstname, :placeholder=>"First Name", :class => "form-control" %>
</div>

<div class="form-group">
     <%= f.text_field :lastname, :placeholder=>"Last Name", :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.text_field :email, :placeholder=>"Email", :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.password_field :password, :placeholder=>"Password", :class => "form-control" %>
</div>

<div class="form-group">
     <%= f.password_field :password_confirmation, :placeholder=>"Password Confirmation",:class => "form-control" %>
</div>

<div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
</div>

<% end %>


<%= link_to "Review A Wine You've Had", new_wine_path, :class => "btn btn-success" %> 

app/views/users/show.html.erb
<% @user.each do |user| %>

<%end%>

app/views/wines/edit.html.erb
<h1>Edit</h1>

<%= form_for @wine do |f| %>

    <div>
         <%= f.text_field :vintage, :placeholder=>"Vintage" %>
    </div>

    <div>
        <%= f.text_field :predominant_variety, :placeholder=>"Predominant Variety"%>
    </div>

    <div>
        <%= f.text_field :country, :placeholder=>"Country" %>
    </div>

    <div>
         <%= f.text_field :region, :placeholder=>"Region"%>
    </div>

    <div>
         <%= f.text_field :producer, :placeholder=>"Producer" %>
    </div>

    <div>
         <%= f.text_field :vineyard, :placeholder=>"Vineyard" %>
    </div>


    <%= f.submit "Submit changes" %>

<% end %>

<%= link_to "Back To Wine List", wines_path %> <br>
<%= link_to "Log Out", logout_path, method: :delete %>

app/views/wines/index.html.erb
<h1>Wines Reviewed By Visitors To Our Site</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Predominant Variety</th>
      <th>Vintage</th>
      <th>Country</th>
      <th>Region</th>
      <th>Producer</th>
      <th>Vineyard</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.predominant_variety %></td>
        <td><%= wine.vintage %></td>
        <td><%= wine.country %></td>
		    <td><%= wine.region %></td>
		    <td><%= wine.producer %></td>
		    <td><%= wine.vineyard %></td>
        <td><%= link_to 'Show & Review', wine_path(wine) %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/wines/new.html.erb
<h1>Review A Wine You've Had!</h1>

<%= form_for @wine do |f| %>

    <div>
         <%= f.text_field :vintage, :placeholder=>"Vintage" %>
    </div>

    <div>
        <%= f.text_field :predominant_variety, :placeholder=>"Predominant Variety"%>
    </div>

    <div>
        <%= f.text_field :country, :placeholder=>"Country" %>
    </div>

    <div>
         <%= f.text_field :region, :placeholder=>"Region"%>
    </div>

    <div>
         <%= f.text_field :producer, :placeholder=>"Producer" %>
    </div>

    <div>
         <%= f.text_field :vineyard, :placeholder=>"Vineyard" %>
    </div>

 
    <%= f.submit "Add" %>

<% end %>

<%= link_to "Back To Wine List", wines_path %> <br>
<%= link_to "Log Out", logout_path, method: :delete %>

app/views/wines/show.html.erb
<p><%= @wine.vintage %> <%= @wine.predominant_variety %> from the <%= @wine.region %> region of <%= @wine.country%>.  The producer is <%= @wine.producer%> and the vineyard is <%= @wine.vineyard%>.</p>


<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comments</th>
      <th>Paired With</th>
      <th>Reviewed By</th>
     </tr>
  </thead>

  <tbody>
    <% @wine.reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comments %></td>
        <td><%= review.paired_with %></td>
	    <td><%= review.user.email%></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to "Add A Review", new_wine_review_path( @wine ) %> <br>
<%= link_to "Back To Wine List", wines_path %> <br>
<%= link_to "Delete", wine_path, method: :delete, data: { confirm: "Are you sure you want to delete this wine?"} %> <br>
<%= link_to "Edit", edit_wine_path( @wine ) %> 